max_Ppp_r = max(max(Ppp_r));
max_Ppp_c = max(max(Ppp_c));
hold on
plot(x, Ppp_r(:, length(z(z<=.05)))/ max_Ppp_r, 'o')
pause(2)
plot(x, Ppp_r(:, length(z(z<=.05)))/ max_Ppp_r)
pause(2)
plot(x, Ppp_c(:, length(z(z<=.05)))/ max_Ppp_c, '+')
pause(2)
plot(x, Ppp_c(:, length(z(z<=.05)))/ max_Ppp_c)
pause(2)
plot(x, Ppp_r(:, length(z(z<=.20)))/ max_Ppp_r, 'o')
pause(2)
plot(x, Ppp_r(:, length(z(z<=.20)))/ max_Ppp_r)
pause(2)
plot(x, Ppp_c(:, length(z(z<=.20)))/ max_Ppp_c, '+')
pause(2)
plot(x, Ppp_c(:, length(z(z<=.20)))/ max_Ppp_c)
pause(2)
plot(x, Ppp_r(:, length(z(z<=.30)))/ max_Ppp_r, 'o')
pause(2)
plot(x, Ppp_r(:, length(z(z<=.30)))/ max_Ppp_r)
pause(2)
plot(x, Ppp_c(:, length(z(z<=.30)))/ max_Ppp_c, '+')
pause(2)
plot(x, Ppp_c(:, length(z(z<=.30)))/ max_Ppp_c)
pause(2)
plot(x, Ppp_r(:, length(z(z<=.40)))/ max_Ppp_r, 'o')
pause(2)
plot(x, Ppp_r(:, length(z(z<=.40)))/ max_Ppp_r)
pause(2)
plot(x, Ppp_c(:, length(z(z<=.40)))/ max_Ppp_c, '+')
pause(2)
plot(x, Ppp_c(:, length(z(z<=.40)))/ max_Ppp_c)